### ISSUE TITLE
error while building with cljsbuild

### ISSUE THREAD

**Issue by murtaza52** [ohpauleez/shoreleave#3]
Hi Paul,

I get the following error when I try building with cljsbuild (lein2 cljsbuild clean) -

java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentVector

These are the entries I have added in my project.clj file - 

:git-dependencies [["https://github.com/ohpauleez/shoreleave.git"]]
:source-paths [[".lein-git-deps/shoreleave/src/"]]

Thanks,
Murtaza

**Comment by ohpauleez** [comment]
Clone this repo, and copy src/shoreleave into your project's src directory:
`cp -R shoreleave/src/shoreleave your_project/src`

Let me know if that works

*EDIT
Also, I promise that a clojars release is coming soon.

**Comment by murtaza52** [comment]
Paul,

Sorry was not able to test out from the source version itself. However I will be trying out the clojars version today!

Also is there a recording of the talk that you gave ? Also any example projects ? 

And why dont you announce it on noir and the clojure list both, I am sure lot of us will find it useful.

Thanks,
Murtaza

**Comment by ohpauleez** [comment]
There are two demo apps that I'm still finishing up.

Once I finish up the few changes to 0.2.2, beef up the documentation, and finish the first app.  I'm going to make the announcement.

The talk wasn't recorded yesterday, but I have been writing the script for a screencast, so that'll pop up soon.

Again, thank you so much for your interest and questions.  If you have any feature request, bugs, or difficulties, let me know,

**Comment by murtaza52** [comment]
If you push the sample apps, I could use their skeleton.

Current things I need to figure out when I tried to create a project -

a) Couldnt find the dependencies to include for the gzip and file-info
middleware ( thus a sample project.clj file)
b) You have given example of api ns, but there is no example on how to use
it from client side.
c) Show all the :require and :use on both client and server side, instead
of just shoreleave specific, as you are also including noir and middleware
functions.

HTML history is fantastic, my current cljs app has no history, and any
press on back button leads to the user going to the login page !

Another needed feature is ability to define routes on client side,
https://github.com/gf3/secretary and snout are good projects. Then a macro
could be written which would map a function call to a route, and would
register that route in history whenever that function is called !

Thanks,
Murtaza

On Thu, Jun 21, 2012 at 5:43 PM, Paul deGrandis <
reply@reply.github.com

**Comment by ohpauleez** [comment]
Hi Murtaza, You can get the slides from my talk in this [blog post](http://www.pauldee.org/blog/)  That might help you with your second question.

I rather not publicly push the demo apps in an incomplete state.  I have no trouble sending you project in it's current state to you directly as a base for you to work off of.  Send me a private message and I'll give you a URL to download the code.

**Comment by murtaza52** [comment]
You can send it to me on murtaza.husain@sevenolives.com.

On Thu, Jun 21, 2012 at 8:57 PM, Paul deGrandis <
reply@reply.github.com

**Comment by si14** [comment]
I would really like to see it too if you don't mind. a2alt@ya.ru

**Comment by ohpauleez** [comment]
Hey guys, I decided to push the example app before it was done because I was getting more questions about setup and configuration.  You can find it on the Shoreleave Org Github page.  It stresses the pubsub, JSONP calls to a separate SOLR server, and Google Maps Geocode service calls.

Additionally you can get a glimpse of "partial renders" and how I use Enfocus.
